version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: eslint
